### ISSUE TITLE
User submitted recipes need to appear consistently throughout the site

### ISSUE THREAD

**Issue by steeznson** [ADover18/recimies#5]
All User recipes need to appear on the index page. Perhaps they ought to be paginated as well, in preparation for there being many recipes at the same time.

Additionally, the user profile page needs to render all recipes from that user. They probably need to be paginated too so that 'power users' can add as many recipes as they like.

**Comment by ADover18** [comment]
Added pagination and infinite scroll functionality to index page and profile recipes.
